###
POST http://localhost:8787/signup HTTP/1.1
Content-Type: application/json

{
"email":"eloirebollo8@gmail.com",
"password":"{{$dotenv %test_password}}"
}

###
POST https://mypr.eloirebollo97.workers.dev/login HTTP/1.1
Content-Type: application/json

{
"email":"eloirebollo2@gmail.com",
"password":"{{$dotenv %test_password}}"
}

###
POST http://localhost:8787/api/call HTTP/1.1
Content-Type: application/json

{"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjYsImVtYWlsIjoiZWxvaXJlYm9sbG84QGdtYWlsLmNvbSIsIm5iZiI6MTc0MTA0MzkxNywiZXhwIjoxNzQxNjQ1MTE3LCJpYXQiOjE3NDEwNDAzMTd9.N1d8VQ6OMHKb569FBQhThzTSC0j0PvJInrvssWimM04"}

###
POST http://localhost:8787/api/nouExercici HTTP/1.1
Content-Type: application/json

{"token":"{{$dotenv %token}}",
"nom":"dominades",
"grupsMusculars":[5,4,3,6]
}

###
POST http://localhost:8787/api/editExercici HTTP/1.1
Content-Type: application/json

{"token":"{{$dotenv %token}}",
"exerciciId":2,
"nom":"Press militar",
"grupsMusculars":[2]
}

###
POST http://localhost:8787/api/nouEntreno HTTP/1.1
Content-Type: application/json

{"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjUsImVtYWlsIjoiZWxvaXJlYm9sbG8zQGdtYWlsLmNvbSIsIm5iZiI6MTc0MTA0NDIwNCwiZXhwIjoxNzQxNjQ1NDA0LCJpYXQiOjE3NDEwNDA2MDR9.cugRzuglfLKA6OeuDugyiYQJ5qPgvl1qnaS4DAcV2ew"}


###
POST http://localhost:8787/api/novaSerie HTTP/1.1
Content-Type: application/json

{"token":"{{$dotenv %token}}",
"entrenoId":3,
"exerciciId":2,
"kg":137,
"reps":2
}

###
POST http://localhost:8787/api/editSerie HTTP/1.1
Content-Type: application/json

{"token":"{{$dotenv %token}}",
"serieId":20,
"entrenoId":3,
"exerciciId":2,
"kg":140,
"reps":3
}

###
POST http://localhost:8787/api/deleteSerie HTTP/1.1
Content-Type: application/json

{"token":"{{$dotenv %tokenUser1}}",
"serieId":6
}

###
POST http://localhost:8787/api/getExercicis HTTP/1.1
Content-Type: application/json

{"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJVc2VySWQiOjUsImV4cCI6MTc0MTY0NjAyNiwiaWF0IjoxNzQxMDQxMjI2fQ.xeq0v0tt-by_M6oh0q5NeW8oVsDKT9IU5t3JaChqLok"}

###
POST http://localhost:8787/api/getEntreno HTTP/1.1
Content-Type: application/json

{"token":"{{$dotenv %token}}",
"entrenoId":3
}

###
POST http://localhost:8787/api/getEntrenos HTTP/1.1
Content-Type: application/json

{"token":"{{$dotenv %token}}",
"dataInici":1735780060,
"dataFi":1772068060
}