###
POST http://localhost:8787/login HTTP/1.1
Content-Type: application/json

{"password":"{{$dotenv %test_password}}",
"email":"eloirebollo97@gmail.com"
}

###
POST http://localhost:8787/api/call HTTP/1.1
Content-Type: application/json

{"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVsb2lyZWJvbGxvOTdAZ21haWwuY29tIiwiVXNlcklkIjoxLCJleHAiOjE3NDA4NTg2MDV9.sxaJxaJedpKtlzVrqvxSWzlXhisavo8Z5aTlxVUK86M"
}

###
POST http://localhost:8787/api/nouExercici HTTP/1.1
Content-Type: application/json

{"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVsb2lyZWJvbGxvOTdAZ21haWwuY29tIiwiVXNlcklkIjoxLCJleHAiOjE3NDA4NTg2MDV9.sxaJxaJedpKtlzVrqvxSWzlXhisavo8Z5aTlxVUK86M",
"nom":"press banca 2",
"grups_musculars":[2]
}

###
GET http://localhost:8787/api/exercicis HTTP/1.1
Content-Type: application/json

{"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVsb2lyZWJvbGxvOTdAZ21haWwuY29tIiwiVXNlcklkIjoxLCJleHAiOjE3NDA4NTg2MDV9.sxaJxaJedpKtlzVrqvxSWzlXhisavo8Z5aTlxVUK86M"
}